name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Diagnose Xcode and project
        run: |
          set -euo pipefail
          xcodebuild -version
          system_profiler SPSoftwareDataType || true
          cd LLMKeyring
          xcodebuild -list -project LLMKeyring.xcodeproj
      - name: Build (no signing)
        run: |
          set -euo pipefail
          cd LLMKeyring
          xcodebuild \
            -project LLMKeyring.xcodeproj \
            -scheme LLMKeyring \
            -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            clean build | tee build-debug.log
        shell: bash
      - name: Upload build log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-debug-log
          path: LLMKeyring/build-debug.log

      - name: Package app artifact
        run: |
          set -euo pipefail
          APP="LLMKeyring/build/Build/Products/Debug/LLMKeyring.app"
          if [ -d "$APP" ]; then
            ditto -c -k --sequesterRsrc --keepParent "$APP" LLMKeyring.app.zip
          else
            echo "App not found: $APP" >&2; exit 1
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LLMKeyring-macos-app
          path: LLMKeyring.app.zip
