name: Release (macOS DMG)

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build app (no signing)
        run: |
          set -euo pipefail
          cd LLMKeyring
          xcodebuild \
            -project LLMKeyring.xcodeproj \
            -scheme LLMKeyring \
            -configuration Release \
            -derivedDataPath build \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Create DMG
        run: |
          set -euo pipefail
          cd LLMKeyring
          APP="build/Build/Products/Release/LLMKeyring.app"
          test -d "$APP"
          mkdir -p dist/LLMKeyring
          cp -R "$APP" dist/LLMKeyring/
          ln -s /Applications dist/LLMKeyring/Applications || true
          hdiutil create -volname "LLMKeyring" -srcfolder dist/LLMKeyring -ov -format UDZO LLMKeyring.dmg
          ditto -c -k --sequesterRsrc --keepParent "$APP" LLMKeyring.app.zip

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LLMKeyring/LLMKeyring.dmg
            LLMKeyring/LLMKeyring.app.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: signing + notarization (requires secrets). Add steps here if you provide Developer ID cert & notary creds.

